services:
  postgres:
    image: postgres:17-alpine
    container_name: takedowntcg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: takedowntcg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - takedowntcg-postgres-data:/var/lib/postgresql/data

volumes:
  takedowntcg-postgres-data:
